In [28]:
import numpy as np
import numpy.linalg as linear

In [29]:
A = np.array([
    [1,1,1,0,0],
    [3,3,3,0,0],
    [4,4,4,0,0],
    [5,5,5,0,0],
    [0,2,0,4,4],
    [0,0,0,5,5],
    [0,1,0,2,2]
])

# U, S, Vt = linear.svd(A, full_matrices=False)
U, S, Vt = linear.svd(A)

In [30]:
# print out the shapes of U, S, Vt and print out the matrices themselves
print('U shape:', U.shape)
# print('U:\n', U)
print('S shape:', S.shape)
print('S:\n', S)
print('Vt shape:', Vt.shape)
# print('Vt:\n', Vt)


U shape: (7, 7)
S shape: (5,)
S:
 [12.48  9.51  1.35  0.    0.  ]
Vt shape: (5, 5)


In [31]:
np.set_printoptions(precision=2, suppress=True)
# print out the diagonal matrix Sigma
print('Sigma:\n', np.diag(S))
print('Sigma:\n', S)

Sigma:
 [[12.48  0.    0.    0.    0.  ]
 [ 0.    9.51  0.    0.    0.  ]
 [ 0.    0.    1.35  0.    0.  ]
 [ 0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.  ]]
Sigma:
 [12.48  9.51  1.35  0.    0.  ]


In [32]:
from numpy.lib.arraysetops import setxor1d
print(S)

[12.48  9.51  1.35  0.    0.  ]


In [33]:
sigma = np.array([
    [12.48, 0, 0, 0, 0],
    [0, 9.51, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0]
])
print('sigma shape:', sigma.shape)
print('sigma:\n', sigma)
print('sigma:\n', np.diag(sigma))

sigma shape: (7, 5)
sigma:
 [[12.48  0.    0.    0.    0.  ]
 [ 0.    9.51  0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.  ]]
sigma:
 [12.48  9.51  0.    0.    0.  ]


In [34]:
# reconstruct A using this new - lower rank matrix sigma

# how big of an effect does dropping the 3rd singular value of sigma, does it have on the data stored in A?
# reconstruct A using this new - lower rank matrix sigma
# sigma[2, 2] = 0
newA = U @ sigma @ Vt
print('newA:\n', newA)


newA:
 [[ 0.99  1.01  0.99 -0.   -0.  ]
 [ 2.98  3.03  2.98 -0.   -0.  ]
 [ 3.98  4.05  3.98 -0.01 -0.01]
 [ 4.97  5.06  4.97 -0.01 -0.01]
 [ 0.36  1.29  0.36  4.08  4.08]
 [-0.37  0.73 -0.37  4.92  4.92]
 [ 0.18  0.65  0.18  2.04  2.04]]


In [35]:
print('A:\n', A)

A:
 [[1 1 1 0 0]
 [3 3 3 0 0]
 [4 4 4 0 0]
 [5 5 5 0 0]
 [0 2 0 4 4]
 [0 0 0 5 5]
 [0 1 0 2 2]]


In [36]:
print(linear.norm(A - newA, ord='fro'))

1.3455608091059477
